---
- name: Dotfiles - Copy dotfiles
  become: no
  git:
    repo=https://github.com/rpbaptist/dotfiles.git
    dest="{{ home_dir }}/.dotfiles"
    update=no

# Replace this script with ansible
# - name: Dotfiles - makesymlinks
#   command: "{{ home_dir }}/.dotfiles/bin/makesymlinks.sh"

- name: Oh My Zsh
  become: no
  git:
    repo=https://github.com/rpbaptist/oh-my-zsh.git
    dest="{{ home_dir }}/.oh-my-zsh"
    update=no

- name: Redshift - configuration
  become: no
  template:
    src="{{ ansible_dir }}/user/files/config/redshift.conf"
    dest="{{ home_dir}}/.config/redshift.conf"
