---
- name: elasticsearch - symlinks exist
  stat: path=/usr/share/elasticsearch/{{ item }}.bak
  register: "{{ item }}"
  with_items:
    - config
    - data
    - logs

- name: elasticsearch - move old symlinks
  command: mv {{ item }} {{ item }}.bak
  when: not "{{ item }}.stat.exists"
  with_items:
    - config
    - data
    - logs

- name: elasticsearch - local directory
  become_user: "{{ user }}"
  file:
    path="{{ home_dir }}/.local/share/elasticsearch/{{ item }}"
    state=directory
  with_items:
    - config
    - data
    - logs

- name: elasticsearch - symlinks
  file:
    src="{{ home_dir }}/.local/share/elasticsearch/{{ item }}"
    dest=/usr/share/elasticsearch/{{ item }}
    state=link
  with_items:
    - config
    - data
    - logs
