---
#- include: intel-graphics.yml
- include: ppa.yml
- include: packages-install.yml
- include: packages-remove.yml
- include: directories.yml
- include: greeter.yml
- include: grub.yml
- include: touchpad.yml
- include: libinput-gestures.yml
- include: power.yml
- include: hosts.yml
- include: openvpn.yml
#- include: copyq.yml
- include: slack.yml
- include: keybase.yml
- include: icons.yml
- include: systemd.yml
