---
- include: ppa.yml
- include: packages-install.yml
- include: directories.yml
- include: papirus.yml
- include: sublime.yml
- include: slack.yml
- include: keybase.yml
- include: touchpad.yml
- include: libinput-gestures.yml
- include: hosts.yml
- include: openvpn.yml
- include: greeter.yml
- include: grub.yml

# - name: Nemo - verify default
#   command: "{{ item }}"
#   with_items:
#     - xdg-mime query default inode/directory application/x-gnome-saved-search
#     - xdg-mime query default application/x-gnome-saved-search
#   register: nemo_default

# - name: Nemo - set default
#   command: xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
#   when: not nemo_default

