---
- include: ppa.yml
# - include: packages-remove.yml
- include: packages-install.yml
- include: sublime.yml
- include: slack.yml
- include: keybase.yml
- include: touchpad.yml
- include: libinput-gestures.yml
- include: hosts.yml
- include: tweaks.yml
