---
- name: Updates apt cache
  apt: update_cache=true

- name: Apps | Install with apt-get
  apt: pkg={{ item }} state=present
  with_items:
    # power management
    - acpi
    - acpi-support
    - tlp
    - tlp-rdw

    # desktop
    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

    # android
    - android-tools-adb
    - android-tools-fastboot

    # input
    - redshift
    - redshift-gtk
    - zsh

    # cinnamon / gnome
    - blueberry
    - cinnamon
    - dconf-tools
    - dconf-editor
    - gnome-icon-theme-full
    - nemo
    - nemo-dropbox
    - nemo-fileroller
    - nemo-seahorse
    - nemo-share
    - python-nemo

    # theming
    - arc-theme

    # internet
    - dropbox
    - duplicity
    - duply
    - google-chrome-stable
    - insync
    - insync-nemo
    - syncthing
    - syncthing-gtk

    # haskell
    - ghc
    - ghc-doc
    - ghc-prof
    - haskell-doc
    - heroku-toolbelt
    - hugs
    - stack

    # java
    - default-jre
    - default-jdk

    # dev environment
    - ctags
    - nodejs
    - python-pip
    - phantomjs
    - docker-engine
    - zeal
    - yarn

    # terminal
    - terminix

    # tools
    - font-manager
    - gdebi
    - git
    - httpie
    - jq
    - keepassx
    - leafpad
    - libinput-tools
    - p7zip-full
    - p7zip-rar
    - ppa-purge
    - python-pip
    - shutter
    - ufw
    - wkhtmltopdf
    - xclip
    - software-properties-gtk
    - synaptic

    # media
    - guvcview
    - pulseaudio-equalizer
    - spotify-client
    - vlc

    # dependencies
    - build-essential
    - cabal-install-1.22
    - cmake
    - cpphs
    - dh-autoreconf
    - libcurl4-openssl-dev
    - libffi-dev
    - libgcrypt11-dev
    - libpq-dev
    - libqt4-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - llvm
    - ncurses-doc
    - python-boto
    - python-gpgme
    - python-software-properties
    - uvcdynctrl
    - wmctrl
    - xdotool
    - zlib1g-dev

    # VPN
    - network-manager
    - network-manager-gnome
    # - network-manager-openvpm
    # - network-manager-openvpm-gnome
