---
- name: Updates apt cache
  apt: update_cache=true

- name: Apps | Install with apt-get
  apt: pkg={{ item }} state=present
  with_items:
    # power management
    - acpi
    - acpi-support
    - tlp
    - tlp-rdw

    # android
    - android-tools-adb
    - android-tools-fastboot

    # input
    - redshift
    - redshift-gtk
    - touchegg
    - zsh

    # cinnamon / gnome
    - blueberry
    - cinnamon
    - dconf-tools
    - dconf-editor
    - gnome-icon-theme-full
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings
    - nemo
    - nemo-dropbox
    - nemo-fileroller
    - nemo-seahorse
    - nemo-share
    - python-nemo
    - vivacious-colors

    # internet
    - dropbox
    - google-chrome-stable
    - insync
    - insync-nemo
    - skype
    - syncthing
    - syncthing-gtk

    # haskell
    - ghc
    - ghc-doc
    - ghc-prof
    - haskell-doc
    - heroku-toolbelt
    - hugs
    - stack

    # dev environment
    - ctags
    - nodejs
    - python-pip
    - phantomjs
    - docker-engine
    # - zeal

    # database
    # Not in repo. Fuck it anyway.
    # - mysql-client-5.6
    - libmysqlclient-dev

    # tools
    - copyq
    - font-manager
    - git
    - httpie
    - keepassx
    - leafpad
    - p7zip-full
    - p7zip-rar
    - ppa-purge
    - python-pip
    - shutter
    - ufw
    - wkhtmltopdf
    - xclip

    # media
    - guvcview
    - pulseaudio-equalizer
    - spotify-client
    - vlc

    # dependencies
    - build-essential
    - cabal-install-1.22
    - cmake
    - cpphs
    - libcurl4-openssl-dev
    - libffi-dev
    - libgcrypt11-dev
    - libpq-dev
    - libqt4-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - llvm
    - ncurses-doc
    - python-gpgme
    - python-software-properties
    - uvcdynctrl
    - zlib1g-dev
