---
- name: Updates apt cache
  apt: update_cache=true

- name: Apps | Install with apt-get
  apt: pkg={{ item }} state=latest
  with_items:
    - ansible
    - build-essential
    - cinnamon
    - cinnamon-translations
    - cmake
    - dropbox
    - folder-color-nemo
    - gconf-editor
    - git
    - gnome-icon-theme-full
    - google-chrome-stable
    - gpaste
    - guvcview
    - heroku-toolbelt
    - httpie
    - leafpad
    - libcurl4-openssl-dev
    - libffi-dev
    - libgcrypt11-dev
    - libqt4-dev
    - libreadline-dev
    - libmysqlclient-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - mysql-client
    - mysql-server
    - nemo
    - nemo-dropbox
    - nemo-fileroller
    - nemo-seahorse
    - nemo-share
    - postgresql-9.5
    - python-gpgme
    - python-nemo
    - python-software-properties
    - redshift
    - redshift-gtk
    - shutter
    - skype
    - spotify-client
    - sqlite3
    - touchegg
    - uvcdynctrl
    - vivacious-colors
    - vivacious-folder-colors-addon
    - vlc
    - xclip
    - zlib1g-dev
    - zsh
