---
- name: Apps | Remove packages which are installed by default
  apt: pkg={{ item }} state=absent
  with_items:
    - ace-of-penguins
    - aisleriot
    - brasero
    - cheese
    - empathy
    - five-or-more
    - four-in-a-row
    - gbrainy
    - gdm
    - gedit
    - gnome-chess
    - gnome-games-common
    - gnome-klotski
    - gnome-mahjongg
    - gnome-mines
    - gnome-nibbles
    - gnome-robots
    - gnome-screensaver
    - gnome-screenshot
    - gnome-sudoku
    - gnome-tetravex
    - gnomine
    - hamster-applet
    - hamster-indicator
    - iagno
    - lightsoff
    - mahjongg
    - nautilus
    - pidgin
    - quadrapassel
    - sound-juicer
    - swell-foop
    - tali
    - thunderbird
    - totem
    - totem-plugins
    - unity-webapps-common
    - webbrowser-app
    - xboard
    - xterm
