---
- name: Updates apt cache
  apt: update_cache=true
  tags:
    - apt
    - ppa

- name: Apps | Install with apt-get
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    # os tools
    - update-manager
    - update-notifier

    # power management
    - acpi
    - acpi-support
    - tlp
    - tlp-rdw

    # greeter
    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

    # android
    - android-tools-adb
    - android-tools-fastboot

    # printing
    - cups

    # usability
    - gnome-characters
    - libinput-tools
    - redshift
    - redshift-gtk

    # desktop environment
    - blueberry
    - cinnamon
    - dconf-tools
    - dconf-editor
    - nemo
    - nemo-dropbox
    - nemo-fileroller
    - nemo-share
    - python-nemo

    # development
    - sublime-text

    # theming
    - arc-theme
    - papirus-icon-theme
    - hardcode-tray
    - breeze-cursor-theme
    #- gnome-icon-theme-full

    # internet
    - chromium-browser
    - chromium-chromedriver
    - dropbox
    - duplicity
    - insync
    - insync-nemo
    - sshuttle
    - transmission

    # office
    - libreoffice

    # dev environment
    - mysql-client
    - python-pip
    #- docker-engine
    - zeal
    - yarn

    # terminal / shell
    - git
    - httpie
    - tilix
    - tree
    - xclip
    - zsh

    # tools
    - baobab
    - curl
    - copyq
    - font-manager
    - gdebi
    - gnome-calculator
    - gnome-disk-utility
    - gnome-system-monitor
    - htop
    - inkscape
    - jq
    - keepassxc
    - leafpad
    - p7zip-full
    - p7zip-rar
    - ppa-purge
    - python-pip
    - shellcheck
    - shutter
    - software-properties-gtk
    - synaptic
    - vim
    - wkhtmltopdf

    # networking
    - gufw
    - ufw
    - network-manager
    - network-manager-gnome
    - network-manager-openvpn
    - network-manager-openvpn-gnome

    # media
    - clementine
    - evince
    - gimp
    - guvcview
    - libasound2-plugin-equal
    - pavucontrol
    - pulseaudio-equalizer
    - spotify-client
    - viewnior
    - vlc

    # dependencies
    - autoconf
    - build-essential
    - cmake
    - cpphs
    - dh-autoreconf
    - libcurl4-openssl-dev
    - libev-dev
    - libffi-dev
    - libgcrypt11-dev
    - libmysqlclient-dev
    - libpango1.0-dev
    - libpq-dev
    - libqt4-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libstartup-notification0-dev
    - libxcb-cursor-dev
    - libxcb-icccm4-dev
    - libxcb-keysyms1-dev
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
    - libxcb1-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libxml2-dev
    - libxslt1-dev
    - libyajl-dev
    - libyaml-dev
    - linux-image-extra-virtual
    - llvm
    - ncurses-doc
    - python-boto
    - python-gpgm
    - python-software-properties
    - sni-qt
    - sni-qt:i386
    - uvcdynctrl
    - wmctrl
    - xdotool
    - zlib1g-dev

  tags: apt
