---
- name: Updates apt cache
  apt: update_cache=true

- name: Apps | Install with apt-get
  apt: pkg={{ item }} state=present
  with_items:
    # power management
    - acpi
    - acpi-support
    - tlp
    - tlp-rdw

    # greeter
    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

    # android
    - android-tools-adb
    - android-tools-fastboot

    # usability
    - libinput-tools
    - redshift
    - redshift-gtk

    # desktop environment
    - blueberry
    - cinnamon
    - dconf-tools
    - dconf-editor
    - nemo
    - nemo-dropbox
    - nemo-fileroller
    - nemo-seahorse
    - nemo-share
    - python-nemo

    # theming
    - arc-theme
    - gnome-icon-theme-full
    - breeze-cursor-theme

    # internet
    - dropbox
    - duplicity
    - google-chrome-stable
    - insync
    - insync-nemo
    - transmission

    # haskell
    - ghc
    - ghc-doc
    - ghc-prof
    - haskell-doc
    - heroku-toolbelt
    - hugs
    - stack

    # office
    - libreoffice

    # java
    - default-jre
    - default-jdk

    # dev environment
    - "mariadb-client-{{ mariadb_version }}"
    - nodejs
    - python-pip
    - phantomjs
    - docker-engine
    - zeal
    - yarn

    # terminal / shell
    - git
    - httpie
    - terminix
    - tree
    - xclip
    - zsh

    # tools
    - baobab
    - font-manager
    - gdebi
    - gnome-calculator
    - gnome-disk-utility
    - gnome-system-monitor
    - htop
    - jq
    - keepassx
    - leafpad
    - p7zip-full
    - p7zip-rar
    - ppa-purge
    - python-pip
    - shutter
    - software-properties-gtk
    - synaptic
    - wkhtmltopdf

    # networking
    - gufw
    - ufw
    - network-manager
    - network-manager-gnome
    - network-manager-openvpm
    - network-manager-openvpm-gnome

    # media
    - evince
    - gimp
    - viewnior
    - clementine
    - guvcview
    - pavucontrol
    - pulseaudio-equalizer
    - spotify-client
    - vlc

    # dependencies
    - build-essential
    - cabal-install-1.22
    - cmake
    - cpphs
    - dh-autoreconf
    - libcurl4-openssl-dev
    - libffi-dev
    - libgcrypt11-dev
    - libmysqlclient-dev
    - libpq-dev
    - libqt4-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - linux-image-extra-virtual
    - llvm
    - ncurses-doc
    - python-boto
    - python-gpgme
    - python-software-properties
    - uvcdynctrl
    - wmctrl
    - xdotool
    - zlib1g-dev
