---
- name: Updates apt cache
  apt: update_cache=true

- name: Apps | Install with apt-get
  apt: pkg={{ item }} state=latest
  with_items:
    - acpi
    - acpi-support
    - android-tools-adb
    - android-tools-fastboot
    - ansible
    - build-essential
    - cabal-install-1.22
    - cinnamon
    - cinnamon-translations
    - cmake
    - cpphs
    - dconf-tools
    - dropbox
    - folder-color-nemo
    - gconf-editor
    - ghc
    - ghc-doc
    - ghc-prof
    - git
    - gnome-icon-theme-full
    - google-chrome-stable
    - guvcview
    - haskell-doc
    - heroku-toolbelt
    - httpie
    - hugs
    - leafpad
    - libcurl4-openssl-dev
    - libffi-dev
    - llvm-3.4
    - ncurses-doc
    - libgcrypt11-dev
    - libmysqlclient-dev
    - libpq-dev
    - libqt4-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - mysql-client
    - mysql-server
    - nemo
    - nemo-dropbox
    - nemo-fileroller
    - nemo-seahorse
    - nemo-share
    - nodejs
    - oracle-java8-installer
    - parcellite
    - postgresql-9.5
    - postgresql-contrib
    - python-gpgme
    - python-nemo
    - python-software-properties
    - redshift
    - redshift-gtk
    - shutter
    - skype
    - spotify-client
    - sqlite3
    - stack
    - tlp
    - tlp-rdw
    - touchegg
    - uvcdynctrl
    - ufw
    - vivacious-colors
    - vivacious-folder-colors-addon
    - vlc
    - xclip
    - zlib1g-dev
    - zsh
