---
- name: Dotfiles - Copy dotfiles
  become_user: "{{ user }}"
  git:
    repo=git@github.com:rpbaptist/dotfiles.git
    dest="{{ home_dir }}/.dotfiles"
    update=yes
    accept_hostkey=yes

# Replace this script with ansible
# - name: Dotfiles - makesymlinks
#   command: "{{ home_dir }}/.dotfiles/bin/makesymlinks.sh"

- name: Oh My Zsh
  become_user: "{{ user }}"
  git:
    repo=git@github.com:rpbaptist/oh-my-zsh.git
    dest="{{ home_dir }}/.oh-my-zsh"
    update=no
    accept_hostkey=yes

# Find a better way to install fonts
# - name: Update font cache
#   command: fc-cache -f -v

- name: Touchegg - config path
  become_user: "{{ user }}"
  file:
    path="{{ home_dir}}/.config/touchegg"
    state=directory

- name: Touchegg - configuration
  become_user: "{{ user }}"
  copy:
    src="{{ ansible_dir }}/richard/files/config/touchegg.conf"
    dest="{{ home_dir}}/.config/touchegg/touchegg.conf"
